### ISSUE TITLE
add_to documentation

### ISSUE THREAD

**Issue by beerlington** [alexgaribay/sendgrid_elixir#5]
I noticed that the put_to function has been renamed add_to, but the docs and readme still refer to put_to. I was going to open a PR to update the docs, but was curious what the reasoning was for the change. What is the significance of `add_*` vs`put_*`?

**Comment by alexgaribay** [comment]
My mistake on the docs.

The reasoning for changing it from `put_to/2` to `add_to/2` and `add_to/3` is because SendGrid's latest API for sending transactional mail made it much easier to deal with multiple recipients. I wanted to make that feature available for people to use. Since the `TO` field can now have a list of recipients, I change the function to `add` since all other places in `SendGrid.Email` that modify lists also use the word `add`. Similarly, all fields that are a single item use the word `put` for manipulation.

If you create a PR for the doc updates I missed, I'll gladly merge.

**Comment by beerlington** [comment]
Will do. Is it possible to assign this issue to me?

**Comment by alexgaribay** [comment]
Unfortunately, I'm unable to assign an issue to you.

**Comment by overallduka** [comment]
That is true, starting to use today and all docs saying about put_to and not add_to. Has none references to this.

**Comment by alexgaribay** [comment]
Latest version correctly uses `add_to` in the docs.
